experiment1:
  groups: [fmnist_dropout_cnn_adam_standard_hpo_algo_1_env_1, fmnist_dropout_cnn_new_gmore_elbo_mean_kl_standard_hpo_algo_1_env_1]
  job_types: [["run_1"], ["run_1, run_2"]]
  runs: [["exp_rep_00", "exp_rep_03"], ["exp_rep_00", "exp_rep_03"]]

  config:
    config_name: 
      values: ["hp_eval_config_0.yml", "hp_eval_config_1.yml"]

  summary:
    best_test_acc:
      min: 0.92
      max: 0.921

experiment2:
  groups: [fmnist_dropout_cnn_adam_standard_hpo_algo_1_env_1, fmnist_dropout_cnn_new_gmore_elbo_mean_kl_standard_hpo_algo_1_env_1]
  runs: [["exp_rep_00", "exp_rep_03"], "all"]
  fields: ["test_loss"]

DEFAULT:
  fields: ["train_acc", "test_acc"]
  entity: kit-alr
  project: wandb_export
  output_path: wandb_data
  output_data_type: numpy