test_experiment:
  groups: [fmnist_dropout_cnn_adam_standard_hpo_algo_1_env_1, torch_script_surrogate_impl_new_gmore_fmnist_cnn]
  job_types: ["all", ["run_1"]]
  runs: "all"

default:
  fields: ["train_acc", "test_acc"]
  entity: kit-alr
  project: wandb_export
  output_path: wandb_data