# custom number of history samples
my_exp_1:
  fields: ["train_loss"]
  history_samples: 100

# export as CSV
my_exp_2:
  fields: ["test_acc", "train_acc"]

  history_samples: 500
  output_data_type: csv

# custom output path
my_exp_3:
  fields: ["mean_eta"]
  output_path: my_data_dir
  output_data_type: csv

# Filter by tags
my_exp_4:
  fields: ["test_acc", "train_acc"]
  tags: [["tag_1", "tag_2"], ["tag_2", "tag_3"]]

DEFAULT:
  entity: kit-alr
  project: wandb_export
  output_path: wandb_data